### ISSUE TITLE
Implement presentation layer input validation and type conversion

### ISSUE THREAD

**Issue by aldy505** [TokoBapak/mock-payment-provider#3]
The input type validation can be done before this specified line of code.

https://github.com/TokoBapak/mock-payment-provider/blob/4ea9f36302d4fda85619a7324bb8e4f329d837ec/presentation/charge_transaction.go#L33-L62

Example for input verification:
```go
var paymentType primitive.PaymentType
switch strings.ToLower(requestBody.PaymentType) {
  case "bca_va":
    paymentType = PaymentTypeVirtualAccountBCA
  case "mandiri_va":
    paymentType = PaymentTypeVirtualAccountMandiri
  // ... and so on forth
  default:
    // return a 400 status code that says invalid payment type (or such)
}
```

**Comment by YogiPristiawan** [comment]
kalau dibikin `map[string]PaymentType` gimana?

**Comment by aldy505** [comment]
> kalau dibikin `map[string]PaymentType` gimana?

Boleh, tapi harus handle semua case dan edge cases:
- Kalo inputnya bener
- Kalo inputnya kosong (empty string)
- Kalo inputnya nggak ada yang sesuai
